# Site
title: Daydream
subtitle:
description: A gentleman should always mean what he says.
keywords:
author: LiHao
timezone:

#menu
menu:
  home: /
  archives: /archives
  tags: /tags
  # categories: /categories
  about: /about

social_links:
  github: https://github.com/chaos1ee
  weibo: https://www.weibo.com/5347775908/profile
  # wechat:
  # qq:
  # instgram:
  # twitter:
  # facebook:
  # email:
  # mobile:

# node-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Markdown-it
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor

# comment
comment:
  livere: MTAyMC80NjIyOC8yMjczOQ==

# evanyou
evanyou: true
